### ISSUE TITLE
Splitting files

### ISSUE THREAD

**Issue by kelvin-acosta** [tjkohli/nebula-ui#14]
When splitting a file left or right the top tab bars are disproportionate. 
![disproportionate tab bar](https://cloud.githubusercontent.com/assets/16613817/22520330/e15ca18c-e881-11e6-94ee-196a9ec17fa0.png)

**Comment by tjkohli** [comment]
What do you mean by the tab bars? The width of the tab bars? The tab bar width is adjustable, and it's always 100% of the width of the pane. You can resize the pane by dragging the vertical divider between them.

As for the tabs, the tabs always auto-size to take all the room available, so that part is working as designed.

**Comment by kelvin-acosta** [comment]
Sorry, I mean the height of the bar. Not sure if its clear enough in the image.

**Comment by tjkohli** [comment]
Thanks! The issue has been resolved and will be included in the next release.

[tab bar](http://tjkoh.li/WbG/5Bw84N7I+)
