### ISSUE TITLE
Active tab styling for files ignored by Git 

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#16]
Hello

Thanks for fixing #7! I don't know if you noticed my last comment on it, but `status-ignored` doesn't seem to be styled yet; it has the same styling as an inactive tab, even if it is active.

I figured I'd post a new ticket since I replied on a closed ticket :-).

Also: the active color is now white for every tab, even if it is modified. Currently you can no longer see that a tab is modified in Git if it's active (only if it's inactive, in which case it will be a dark green). Was it perhaps intentional that the color isn't green (but faded out) when inactive and green (full brightness) when active?

Thanks in advance

**Comment by tjkohli** [comment]
1. Will investigate & resolve the `status-ignored` issue.

2. The active tag color is by design. Anything other than white does not provide enough contrast to define the selected tab. Knowing a tab is active is more critical than knowing if a tab has been modified in the VCS or not. If you look carefully, the close (X) button on each tab still retains the VCS color.

**Comment by tjkohli** [comment]
Fixed. Will release with 0.6.0. Thanks!
